server:
  port: 8084

logging:
  level:
    root: info
    com.etaksify.ms: debug

spring:
  application:
    name: ms-etaskify-tasks
  datasource:
    url: jdbc:postgresql://localhost:5432/taskify_tasks
    username: etaskify
    password: etaskify_123
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
  jpa:
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    template:
      retry:
        enabled: true
        max-attempts: 2
  mvc:
    converters:
      preferred-json-mapper: gson

feign:
  client:
    config:
      default:
        connectTimeout: 30_000 #ms
        readTimeout: 30_000 #ms
        loggerLevel: FULL

client:
  user:
    url: http://localhost:8082

queue:
  taskify-notify: TASKIFY_NOTIFY_Q
